# Pandas

In [1]:
import pandas as pd

In [ ]:
data = [1,2,3,4,5,6]
s1 = pd.Series(data,)

In [7]:
print(s1)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [8]:
s2 = pd.Series(data,index = ['a','b','c','d','e','f'],name = 'Numbers')
print(s2)

a    1
b    2
c    3
d    4
e    5
f    6
Name: Numbers, dtype: int64

In [9]:
data = {'a':10,'b':20,'c':30}
s3 = pd.Series(data)
print(s3)

a    10
b    20
c    30
dtype: int64

In [18]:
s4 = pd.Series([10,20,30,40,50,60],index = ['a','b','c','d','e','f'],name = 'Scores')
print(s4.index)
print(s4.values)
print(s4.name)
print(s4.dtype)
print(s4.shape)
type(s4.shape)

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')
[10 20 30 40 50 60]
Scores
int64
(6,)

tuple

### Series Indexing and Access

In [24]:
#LAbel based index
print(s4[0])
print(s4['a'])

10
10

C:\Users\DVWG3375\AppData\Local\Temp\ipykernel_16588\4005727960.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s4[0])

### positional Indexing

In [21]:
print(s4.values[3])

40

### iloc Indexing

In [22]:
print(s4.iloc[1:4])

b    20
c    30
d    40
Name: Scores, dtype: int64

### .loc[] uses the Label/Index name, not position

In [26]:
print(s4[['b','d']])
print(s4.loc[['b','d']])

b    20
d    40
Name: Scores, dtype: int64
b    20
d    40
Name: Scores, dtype: int64

In [35]:
s4.loc[[1,3]]

KeyError: "None of [Index([1, 3], dtype='int32')] are in the [index]"

In [36]:
data = {
    'Name' : ['Mayank','Goyal','Hohn'],
    'Age' :[26,27,40],
    'City' : ['Delhi','Gurgaon','ABC']
}

In [38]:
df = pd.DataFrame(data)

In [39]:
df

     Name  Age     City
0  Mayank   26    Delhi
1   Goyal   27  Gurgaon
2    Hohn   40      ABC

In [57]:
Records = [
    {'Name':'Mayank','Age' :26,'City': 'Delhi'},
    {'Name':'Mayank','Age' :70,'City': 'Delhi'},
    {'Name':'Mayank','Age' :71,'City': 'Delhi'}
]

In [58]:
df = pd.DataFrame(Records)

In [43]:
df

     Name  Age   City
0  Mayank   26  Delhi
1  Mayank   26  Delhi
2  Mayank   26  Delhi

In [47]:
print(df['Name'])
print("==========")
print(df[['Name','Age']])

0    Mayank
1    Mayank
2    Mayank
Name: Name, dtype: object
==========
     Name  Age
0  Mayank   26
1  Mayank   26
2  Mayank   26

In [45]:
print(df.values)

[['Mayank' 26 'Delhi']
 ['Mayank' 26 'Delhi']
 ['Mayank' 26 'Delhi']]

In [50]:
print(df.loc[0])
print("+++++++++++++")
print(df.iloc[0])

Name    Mayank
Age         26
City     Delhi
Name: 0, dtype: object
+++++++++++++
Name    Mayank
Age         26
City     Delhi
Name: 0, dtype: object

# Conditional Selection (Boolean Indexing)

In [62]:
# df['Age']<70
# [df['Age']<70]
older =df[df['Age']>=70]

In [63]:
older.shape

(2, 3)

In [64]:
older.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 1 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
 2   City    2 non-null      object
dtypes: int64(1), object(2)
memory usage: 64.0+ bytes

In [ ]:
older.describe()

             Age
count   2.000000
mean   70.500000
std     0.707107
min    70.000000
25%    70.250000
50%    70.500000
75%    70.750000
max    71.000000